services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: stroycontrol-db
    environment:
      POSTGRES_USER: stroycontrol_user
      POSTGRES_PASSWORD: stroycontrol_pass
      POSTGRES_DB: stroycontrol
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stroycontrol_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: