spring:
  config:
    activate:
      on-profile: dev

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/msi_db
    username: msi_user
    password: msi_password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    clean-on-validation-error: true

  jpa:
    hibernate:
      ddl-auto: validate  # Изменено с update на validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always  # Добавлено для поддержки data.sql

logging:
  level:
    root: INFO
    dev.msi_hackaton.backend_app: DEBUG
    org.springframework.web.socket: INFO
    org.springframework.messaging: INFO
    org.hibernate.SQL: INFO
    org.flywaydb.core: INFO