spring:
  application:
    name: backend_app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "Annotations (Code)"
        url: /v3/api-docs
      - name: "Custom YAML"
        url: /v3/api-docs-yaml
    defaultModelsExpandDepth: -1
  api-docs:
    enabled: true
    paths-to-match: /api/**

storage:
  local:
    directory: ./storage

token:
  signing:
    key: ${KEY:KcSZ0Vl23T7U9F2B7b/Qx9xH8m/zD63vW5Y4t/5Xl0J5v0bK6w74+0q4hI8rG1Fm67k8b9aM7/vY9V+k6T64eQ==}
  expiration: 86400000

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: files